import type { Theme } from './types'

export const THEMES: Theme[] = [
  {
    id: 1,
    title: 'O que é tokenização imobiliária?',
    hook: 'Você sabia que agora é possível investir em imóveis de alto padrão com apenas R$100?',
    keywords: ['luxury real estate', 'modern architecture'],
    tone: 'educational',
  },
  {
    id: 2,
    title: 'O que é o BEM CONCRETO TOKEN?',
    hook: 'O BEM é um token digital que representa sua participação em imóveis reais.',
    keywords: ['real estate investment', 'digital token'],
    tone: 'informational',
  },
  {
    id: 3,
    title: 'Como funciona juridicamente o BEM?',
    hook: 'Segurança jurídica é a base do BEM CONCRETO TOKEN.',
    keywords: ['real estate contract', 'legal document'],
    tone: 'educational',
  },
  {
    id: 4,
    title: 'O que é RWA — Real World Assets?',
    hook: 'RWA é a revolução que conecta o mundo físico ao blockchain.',
    keywords: ['blockchain real estate', 'digital assets'],
    tone: 'educational',
  },
  {
    id: 5,
    title: 'Invista em imóveis a partir de R$100',
    hook: 'Imóveis de alto padrão acessíveis para qualquer pessoa.',
    keywords: ['luxury apartment', 'property investment'],
    tone: 'motivational',
  },
  {
    id: 6,
    title: 'BEM vs FII: qual é melhor?',
    hook: 'Você já comparou o BEM com os Fundos de Investimento Imobiliário?',
    keywords: ['investment comparison', 'real estate fund'],
    tone: 'educational',
  },
  {
    id: 7,
    title: 'Blockchain Polygon: a tecnologia por trás do BEM',
    hook: 'O BEM roda na Polygon, uma das blockchains mais rápidas e baratas do mundo.',
    keywords: ['blockchain technology', 'crypto real estate'],
    tone: 'educational',
  },
  {
    id: 8,
    title: 'Transparência total: verifique seu investimento on-chain',
    hook: 'Cada BEM emitido pode ser rastreado publicamente na blockchain.',
    keywords: ['transparent investment', 'blockchain verification'],
    tone: 'informational',
  },
  {
    id: 9,
    title: 'Como o preço do BEM sobe com o tempo?',
    hook: 'O modelo de tranches garante que o preço do BEM só cresce.',
    keywords: ['investment growth', 'property value'],
    tone: 'educational',
  },
  {
    id: 10,
    title: 'As 6 tranches de emissão do BEM',
    hook: 'Quem entra cedo, paga menos. Essa é a lógica das tranches.',
    keywords: ['investment strategy', 'early investor'],
    tone: 'urgency',
  },
  {
    id: 11,
    title: 'O que é SCP — Sociedade em Conta de Participação?',
    hook: 'O BEM usa SCP para garantir que seu investimento seja seguro e lucrativo.',
    keywords: ['business partnership', 'real estate company'],
    tone: 'educational',
  },
  {
    id: 12,
    title: 'Leilão de imóveis: como o BEM compra com até 50% de desconto',
    hook: 'A estratégia mais lucrativa do mercado imobiliário começa no leilão.',
    keywords: ['property auction', 'real estate deal'],
    tone: 'informational',
  },
  {
    id: 13,
    title: 'Incorporação imobiliária: a fase mais lucrativa',
    hook: 'Investir na planta é a forma mais rentável de entrar no mercado imobiliário.',
    keywords: ['real estate development', 'construction investment'],
    tone: 'educational',
  },
  {
    id: 14,
    title: 'Como funciona a liquidez do BEM?',
    hook: 'Diferente de imóveis físicos, o BEM tem liquidez programada.',
    keywords: ['liquid investment', 'real estate liquidity'],
    tone: 'informational',
  },
  {
    id: 15,
    title: 'Por que o prazo de liquidação é 180 dias?',
    hook: '180 dias: tempo suficiente para maximizar o retorno do seu investimento.',
    keywords: ['investment timeline', 'financial planning'],
    tone: 'educational',
  },
  {
    id: 16,
    title: 'Como os imóveis do portfólio BEM são selecionados?',
    hook: 'Cada imóvel passa por um rigoroso processo de curadoria.',
    keywords: ['luxury property selection', 'high end real estate'],
    tone: 'informational',
  },
  {
    id: 17,
    title: 'Quanto rende o BEM?',
    hook: 'Já imaginou seu dinheiro rendendo mais do que a poupança investido em imóveis?',
    keywords: ['investment returns', 'financial growth'],
    tone: 'motivational',
  },
  {
    id: 18,
    title: 'Quem pode investir em BEM?',
    hook: 'Qualquer pessoa com R$100 pode se tornar investidora imobiliária.',
    keywords: ['accessible investment', 'real estate for everyone'],
    tone: 'motivational',
  },
  {
    id: 19,
    title: 'Como se tornar consultor BEM',
    hook: 'Ganhe comissão de 4% em cada investimento dos seus indicados.',
    keywords: ['real estate consultant', 'passive income'],
    tone: 'motivational',
  },
  {
    id: 20,
    title: 'Renda passiva: 4% em cada indicação',
    hook: 'Seu cliente investe hoje. Você ganha para sempre.',
    keywords: ['passive income', 'referral program'],
    tone: 'motivational',
  },
  {
    id: 21,
    title: 'BEM não é especulação — é ativo real',
    hook: 'Diferente de criptomoedas especulativas, o BEM tem lastro em imóveis físicos.',
    keywords: ['real asset', 'stable investment'],
    tone: 'educational',
  },
  {
    id: 22,
    title: 'Por que imóveis são o investimento mais seguro?',
    hook: 'Imóveis nunca foram a zero na história econômica do Brasil.',
    keywords: ['safe investment', 'real estate stability'],
    tone: 'educational',
  },
  {
    id: 23,
    title: 'Como a blockchain protege seu investimento',
    hook: 'Seu token BEM é imutável, rastreável e inviolável.',
    keywords: ['blockchain security', 'crypto protection'],
    tone: 'informational',
  },
  {
    id: 24,
    title: 'BEM vs poupança vs CDB: a comparação honesta',
    hook: 'Vamos comparar o BEM com os investimentos mais populares do Brasil.',
    keywords: ['investment comparison', 'financial education'],
    tone: 'educational',
  },
  {
    id: 25,
    title: 'O ecossistema completo BEM CONCRETO',
    hook: 'App do investidor, plataforma de consultores, certificação — tudo integrado.',
    keywords: ['investment ecosystem', 'fintech platform'],
    tone: 'informational',
  },
  {
    id: 26,
    title: 'Como funciona o app do investidor BEM?',
    hook: 'Compre, venda e acompanhe seus tokens BEM com um clique.',
    keywords: ['investment app', 'mobile banking'],
    tone: 'informational',
  },
  {
    id: 27,
    title: 'Auditoria e segurança: o que garante o BEM?',
    hook: 'CNPJ ativo, contrato na blockchain, dados auditáveis a qualquer momento.',
    keywords: ['financial security', 'investment audit'],
    tone: 'informational',
  },
  {
    id: 28,
    title: 'O futuro da tokenização imobiliária no Brasil',
    hook: 'O mercado de RWA no Brasil deve movimentar bilhões até 2030.',
    keywords: ['future real estate', 'blockchain Brazil'],
    tone: 'educational',
  },
  {
    id: 29,
    title: 'Como sacar seus tokens BEM para a carteira',
    hook: 'Seus tokens BEM são seus. Guarde-os na sua carteira Polygon.',
    keywords: ['crypto wallet', 'token withdrawal'],
    tone: 'educational',
  },
  {
    id: 30,
    title: 'Diversificação: BEM como parte do seu portfólio',
    hook: 'Não coloque todos os ovos na mesma cesta — adicione BEM ao seu portfólio.',
    keywords: ['portfolio diversification', 'investment strategy'],
    tone: 'educational',
  },
  {
    id: 31,
    title: 'Imóveis de alto padrão para todos',
    hook: 'A democratização do investimento imobiliário chegou.',
    keywords: ['luxury real estate access', 'democratize investment'],
    tone: 'motivational',
  },
  {
    id: 32,
    title: 'A missão da Bem Concreto',
    hook: 'Tornar o investimento imobiliário acessível para qualquer brasileiro.',
    keywords: ['company mission', 'real estate Brazil'],
    tone: 'informational',
  },
  {
    id: 33,
    title: 'Por que investir agora na Tranche 1?',
    hook: 'Na Tranche 1, o BEM custa U$0,60. Na Tranche 2, custará U$1,20.',
    keywords: ['investment opportunity', 'early stage'],
    tone: 'urgency',
  },
  {
    id: 34,
    title: 'SPE: a estrutura jurídica que protege seu investimento',
    hook: 'Cada imóvel tem sua própria SPE — seu capital nunca se mistura.',
    keywords: ['legal structure', 'investment protection'],
    tone: 'educational',
  },
  {
    id: 35,
    title: 'Tokenização: o elo entre tijolo e blockchain',
    hook: 'O BEM conecta o mercado imobiliário mais tradicional ao mais inovador.',
    keywords: ['tokenization', 'real estate blockchain'],
    tone: 'educational',
  },
]

export function getTodayTheme(): Theme {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000
  )
  return THEMES[dayOfYear % THEMES.length]
}
